### ISSUE TITLE
Unexpected response of ``TGOV1`` series

### ISSUE THREAD

**Issue by jinningwang** [CURENT/andes#583]
**Describe the bug**

I expect following two groups should response the same when dbL and dbU are zeros: 1) TGOV1N vs. TGOV1NDB; 2) TGOV1 vs. TGOV1DB

But they are different, did I misunderstand anything?

![image](https://github.com/user-attachments/assets/cf465690-4d1d-48a9-9eb7-2ed0ed9d0a3f)

**To Reproduce**

More can be seen in this demo: https://github.com/CURENT/demo/blob/master/demo/TGOV1/TGOV1_variants.ipynb

**Expected behavior**

**Desktop (please complete the following information):**

 - OS: [e.g. Windows]
 - ANDES version (please paste the output from `andes misc --version`)

**pip packages (please paste the output from `pip list`)

**Additional context**

**Comment by cuihantao** [comment]
We expect two groups of overlapping curves but are getting three curves. One of them is off. Two of them should overlap but do not. Check if something is off in the corresponding case file and model. On Dec 4, 2024, at 9:00 PM, Jinning Wang ***@***.***> wrote:﻿
Describe the bug
I expect following two groups should response the same when dbL and dbU are zeros: 1) TGOV1N vs. TGOV1NDB; 2) TGOV1 vs. TGOV1DB
But they are different, did I misunderstand anything?
image.png (view on web)
To Reproduce
More can be seen in this demo: https://github.com/CURENT/demo/blob/master/demo/TGOV1/TGOV1_variants.ipynb
Expected behavior
A clear and concise description of what you expected to happen.
Desktop (please complete the following information):

OS: [e.g. Windows]
ANDES version (please paste the output from andes misc --version)

**pip packages (please paste the output from pip list)
Additional context
Add any other context about the problem here.

**Comment by jinningwang** [comment]
The updated figure is below. There are two overlapped curves, which makes sense. However, why the two groups are not overlapped? I expect when dbL and dbU are zeros, DeadBand can be regarded as a gain with k=1?

![image](https://github.com/user-attachments/assets/aca04e64-23d4-4803-8c9f-32bb9dd3b602)

**Comment by cuihantao** [comment]
That’s why TGOV1 and TGOV1N are two different models. The droop is moved. See the doc string of TGOV1N. Sent from my iPhoneOn Dec 4, 2024, at 11:19 PM, Jinning Wang ***@***.***> wrote:﻿
The updated figure is below. There are two overlapped curves, which makes sense. However, why the two groups are not overlapped? I expect when dbL and dbU are zeros, DeadBand can be regarded as a gain with k=1?
image.png (view on web)

**Comment by jinningwang** [comment]
Thanks for the info.
